### PR TITLE
Custom data attribute into each node

### PR DESCRIPTION
**Pull request by davidt22**
I have added a custom data attribute to be used to store any type of data related with a node element to be used for our own actions, like read it via AJAX and do some actions.

It is only added if you add it into the JSON data.

The JSON has to be something like this: 

`var tree = [
            {
                text: "Parent 1",
                custom: 233,
                nodes: [
                    {
                        text: "Child 1",
                        custom: 235,
                        nodes: [
                            {
                                text: "Grandchild 1"
                                custom: 236,
                            },
                            {
                                text: "Grandchild 2"
                               custom: 239,
                            }
                        ]
                    },
        ];`

### CODE REVIEW

**Comment by lawtatfaitony** [comment]
how to use

**Comment by davidt22** [comment]
@lawtatfaitony you must include into your JSON data an attribute named 'custom' and the value of that attribute, like my example in the first message of this PR.

**Comment by lawtatfaitony** [comment]
thank you very much!!!!
I  see

**Review by mojoaxel — APPROVED** [review]

**Comment by begin29** [comment]
@davidt22 I am a bit confused, because that feature is not exist on jonmiles original repository.
@jonmiles Have you reverted 'custom attribute' feature?

**Pull request closed without merging**
