### PR TITLE
addNode method added.

### PR DESCRIPTION
**Pull request by lxsameer**
addNode method added to treeview in order to add a new node under an already exists node. Now adding node under another node would be easy and painless

### CODE REVIEW

**Comment by hgillh** [comment]
@lxsameer ,

I really need this method as I need to dynamically add nodes under parents(through ajax). 
Is there any possibility to add multiple  nodes under a parent node ?
Also, can you please give me an example of how can I use your addNode method ?

Thanks in advance

**Comment by ChadSikorra** [comment]
This is really needed. That or some sort of url callback option like jstree does:

```
$('#tree').jstree({
'core' : {
  'data' : {
    'url' : function (node) {
      return node.id === '#' ?
        'ajax_roots.json' :
        'ajax_children.json';
    },
    'data' : function (node) {
      return { 'id' : node.id };
    }
  }
});
```

There isn't an easy way to dynamically expand nodes via ajax otherwise. Currently I use a backbone view to generate the tree and I keep track of childnodes in a hash within the view, then I re-render the tree with all children on an expand event :/

**Comment by antonu17** [comment]
Why you did not inspect the project first? It was already added in 22172d83be84469828499037172ec46a20a2632f

**Comment by ChadSikorra** [comment]
Apparently I have not had enough coffee this morning. It looks like the `develop` branch has both the `addNodes()` method and a `dataUrl` option for ajax. Nice to know. Though kinda confusing...I expected to see that on master.

**Pull request closed without merging**
