### PR TITLE
opens links on new tab with option linksOnNewTab

### PR DESCRIPTION
**Pull request by carvilsi**
Hi!

The idea of this pull request is, allow to open the linked document in a new tab:
#### linksOnNewTab

Boolean.  Default: false

In conjunction with _enableLinks_ set to true, opens the linked document in a new tab.

I hope this can be useful 😄

### CODE REVIEW

**Comment by slolo2000** [comment]
Very very useful, thanks a lot!
I really hope it will be merge in the base branch.

**Comment by carvilsi** [comment]
@slolo2000 thanks 👍 

I hope too!

**Comment by jonmiles** [comment]
Sorry but this will not be merged.  Link support has been dropped in v2.0 and you should use custom event handlers i.e. nodeSelected.  

With custom events you can implement any functionality you required, update tabs, panels etc. and you have full control.

**Comment by slolo2000** [comment]
Thanks jonmiles for your answer.
You are absolutly right, using onNodeSelected event work like a charm using window.open inside the function.

**Pull request closed without merging**
