### PR TITLE
Update ExpressJS to the latest version

### PR DESCRIPTION
**Pull request by skateman**
The old 3.x versions are no longer maintained.
Also their dependencies can cause security issues.

### CODE REVIEW

**Comment by andresgalante** [comment]
👍

**Comment by priley86** [comment]
+1

**Comment by jonmiles** [comment]
Express is a development tool not part of the distributable, there's no validity to this request.

**Comment by skateman** [comment]
@jonmiles you're right, sorry, I missed that with the one in the [master branch](https://github.com/jonmiles/bootstrap-treeview/blob/master/package.json#L35)

**Pull request closed without merging**
